# Generated by Django 5.1.1 on 2024-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_atributentery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributentery',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
